name: Feature Request
description: Suggest an idea or enhancement for httpx.zig
title: "[Feat]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving httpx.zig!

  - type: textarea
    id: pitch
    attributes:
      label: Pitch
      description: A clear and concise description of the feature you want.
      placeholder: "I would like to support protocol X..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
