name: Help Wanted
description: Ask a question or request assistance
title: "[Help]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Please check the [documentation](https://muhammad-fiaz.github.io/httpx.zig/) first.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: provide any code snippets or context that might help us answer your question.
